# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZjVlYmVmOTBkMDI0NjRjODAzZmU1OWRmMTdlNWJiZWQxNjA5ZmM1MGFjNGE3NTlkMjk4OWNiNjcxNmE5NzJkZDQzN2UwZmJjZjBlOWJhZmU2M2Q4NGMyNjcwNzg0NTU3NjUzZWM2NmIyYmI4MzVmMjM4YTY1ZTdhNjI2ZTg0ODk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
